apiVersion: v1
kind: Service
metadata:
  name: cloud-resource-service
spec:
  selector:
    app: cloud-resource-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
